version: '3.3'
services:
  mysql:
    deploy:
      replicas: 10
    build:
      dockerfile: docker/mysql.Dockerfile
      args:
        - MYSQL_DATABASE=raven
        - MYSQL_USER=admin
        - MYSQL_PASSWORD=secret
        - MYSQL_ROOT_PASSWORD=toor
    ports:
      - "3306:3306"

#  api:
#    build:
#      context: api
