  name: Mandatory requirements
  run-name: ${{ github.event.head_commit.message }} - ${{ github.sha }}

  on: [ push ]
  jobs:
    build:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v4
        - uses: bazelbuild/setup-bazelisk@v2
        - name: Mount bazel cache  # Optional
          uses: actions/cache@v3
          with:
            path: "~/.cache/bazel"
            key: bazel
        - run: > 
            bazel build //... && \
            bazel test //...