  name: BuilderTester
  run-name: ${{ github.event.head_commit.message }}

  on: [ push ]
  jobs:
    build:
      name: builder
      runs-on: ubuntu-22.04
      steps:
        - uses: actions/checkout@v4
        - uses: actions/setup-java@v3
          with:
            distribution: 'zulu'
            java-version: '17'
        - uses: bazelbuild/setup-bazelisk@v2
        - name: Mount bazel cache
          uses: actions/cache@v3
          with:
            path: "~/.cache/bazel"
            key: bazel
        - run: |
            bazel build //...
    test:
      name: tester
      runs-on: ubuntu-22.04
      steps:
        - uses: actions/checkout@v4
        - uses: actions/setup-java@v3
          with:
            distribution: 'zulu'
            java-version: '17'
        - uses: bazelbuild/setup-bazelisk@v2
        - name: Mount bazel cache
          uses: actions/cache@v3
          with:
            path: "~/.cache/bazel"
            key: bazel
        - run: |
            bazel test //...
      needs: [ build ]