  name: Builder
  run-name: ${{ github.event.head_commit.message }} - ${{ github.sha }}

  on: [push]
  jobs:
    build:
      runs-on: ubuntu-latest
      steps:
        - run: > 
            bazel build //...