  name: BuilderTester
  run-name: ${{ github.event.head_commit.message }}

  on: [ push ]
  jobs:
    build:
      name: build_and_test
      runs-on: ubuntu-22.04
      steps:
        - uses: actions/checkout@v4
        - uses: actions/setup-java@v3
          with:
            distribution: 'zulu'
            java-version: '17'
        - uses: bazelbuild/setup-bazelisk@v2
#        - name: Mount bazel cache  # Optional
#          uses: actions/cache@v3
#          with:
#            path: "~/.cache/bazel"
#            key: bazel
        - run: > 
            bazel build //...
        - uses: actions/upload-artifact@v3
          with:
            name: build-files
            path: bazel-bin/raven/run_local
            retention-days: 1